"""Second migration

Revision ID: 92dd75f106c0
Revises: 7239092fb79b
Create Date: 2024-08-21 02:57:01.680198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dd75f106c0'
down_revision: Union[str, None] = '7239092fb79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.String(length=50), nullable=True),
    sa.Column('ram', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vms')
    # ### end Alembic commands ###
