[tool.poetry]
name = "rancher_api"
version = "0.1.0"
description = "Hexagonal Arch"
authors = ["Adil"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.12"
paramiko = "^3.4.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
